apiVersion: v1
kind: ConfigMap
metadata:
  name: jcode-backend-config
  namespace: watcher
data:
  SPRING_APPLICATION_NAME: "jcodehub"

  SERVER_PORT: "8080"

  # 에러 메세지 다국어
  SPRING_MESSAGES_BASENAME: "ValidationMessages"
  SPRING_MESSAGES_FALLBACKTOSYSTEMLOCALE: "false"
  SPRING_MESSAGES_ENCODING: "UTF-8"

  # prometheus 설정
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "prometheus,health,info"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_SERVER_PORT: "8080"

  # domain
  FRONT_DOMAIN: "https://front.example.com"
  ROUTER_DOMAIN: "https://router.example.com"

  # Service Url
  ROUTER_URL: "https://router.example.com/jcode/"
  WATCHER_URL: "https://watcher.example.com"
  GENERATOR_URL: "https://generator.example.com"

  # Keycloak OAuth2
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTID: "myclient"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATIONGRANTTYPE: "authorization_code"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_REDIRECTURI: "https://exmaple.com/login/oauth2/code/keycloak"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE: "openid, profile, email"

  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATIONURI: "https://keycloak.example.com/realms/myrealms/protocol/openid-connect/auth"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKENURI: "https://keycloak.example.com/realms/myrealms/protocol/openid-connect/token"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USERINFOURI: "https://keycloak.example.com/realms/myrealms/protocol/openid-connect/userinfo"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWKSETURI: "https://keycloak.example.com/realms/myrealms/protocol/openid-connect/certs"
  SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USERNAMEATTRIBUTE: "email"

  # Keycloak JWKS URL
  KEYCLOAK_JWKSURL: "https://keycloak.example.com/realms/myrealms/protocol/openid-connect/certs"
  KEYCLOAK_LOGOUT_URL: "https://keycloak.example.com/realms/myrealms/protocol/openid-connect/logout"

  # redirect - set connection timeout
  SERVER_TOMCAT_CONNECTIONTIMEOUT: "120000"
  SERVER_SERVLET_SESSION_TIMEOUT: "120s"

  # DB:
  # master / slave 설정
  SPRING_DATASOURCE_MASTER_HIKARI_DRIVERCLASSNAME: "org.mariadb.jdbc.Driver"
  SPRING_DATASOURCE_MASTER_HIKARI_JDBCURL: "jdbc:mariadb://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=KST"
  SPRING_DATASOURCE_MASTER_HIKARI_USERNAME: "user"

  SPRING_DATASOURCE_MASTER_HIKARI_MAXIMUMPOOLSIZE: "500"
  SPRING_DATASOURCE_MASTER_HIKARI_MINIMUMIDLE: "10"
  SPRING_DATASOURCE_MASTER_HIKARI_CONNECTIONTIMEOUT: "30000"
  SPRING_DATASOURCE_MASTER_HIKARI_IDLETIMEOUT: "600000"
  SPRING_DATASOURCE_MASTER_HIKARI_MAXLIFETIME: "1800000"
  SPRING_DATASOURCE_MASTER_HIKARI_LEAKDETECTIONTHRESHOLD: "5000"

  SPRING_DATASOURCE_REPLICA_HIKARI_DRIVERCLASSNAME: "org.mariadb.jdbc.Driver"
  SPRING_DATASOURCE_REPLICA_HIKARI_JDBCURL: "jdbc:mariadb://localhost2:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=KST"
  SPRING_DATASOURCE_REPLICA_HIKARI_USERNAME: "user"
  SPRING_DATASOURCE_REPLICA_HIKARI_CONNECTIONTIMEOUT: "1300"
  SPRING_DATASOURCE_REPLICA_HIKARI_VALIDATIONTIMEOUT: "700"

  SPRING_DATASOURCE_REPLICA_HIKARI_MAXIMUMPOOLSIZE: "500"
  SPRING_DATASOURCE_REPLICA_HIKARI_MINIMUMIDLE: "5"
  SPRING_DATASOURCE_REPLICA_HIKARI_IDLETIMEOUT: "30000"
  SPRING_DATASOURCE_REPLICA_HIKARI_MAXLIFETIME: "1800000"
  SPRING_DATASOURCE_REPLICA_HIKARI_LEAKDETECTIONTHRESHOLD: "5000"

  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MariaDBDialect"

  SPRING_JPA_HIBERNATE_DDLAUTO: "none"

  # Redis
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"

  # jwt
  JWT_EXPIRE: "600000"
  JWT_REFRESH_EXPIRE: "21600000"
  JWT_COOKIE_DOMAIN: "example.com"

  # courseKey charset (강의 키 생성 시 사용되는 문자 집합)
  COURSE_KEY_CHARSET: "ABCDEFGHIJKLMNOPQRSTUVWXYZ..."

  # Swagger UI
  SPRINGDOC_SWAGGERUI_ENABLED: "true"
  SPRINGDOC_SWAGGERUI_PATH: "index.html"

  SPRINGDOC_APIDOCS_ENABLED: "true"
  SPRINGDOC_APIDOCS_PATH: "/v3/api-docs"

  SPRINGDOC_SWAGGERUI_DISABLESWAGGERDEFAULTURL: "true"

  # logging
  LOGGING_FILE_PATH: "/logs"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: "DEBUG"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: "DEBUG"

---

apiVersion: v1
kind: Secret
metadata:
  name: jcode-backend-secret
  namespace: watcher
type: Opaque
data:
  # Keycloak OAuth2 (myclientSecret)
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTSECRET: "bXljbGllbnRTZWNyZXQ="

  # DB: (password)
  SPRING_DATASOURCE_MASTER_HIKARI_PASSWORD: "cGFzc3dvcmQ="
  SPRING_DATASOURCE_REPLICA_HIKARI_PASSWORD: "cGFzc3dvcmQ="

  # Redis
  REDIS_PASSWORD: "cGFzc3dvcmQ="

  # jwt (jwtSecret, jwtRefreshSecret)
  JWT_SECRET: "and0U2VjcmV0"
  JWT_REFRESH_SECRET: "and0UmVmcmVzaFNlY3JldA=="
